### ISSUE TITLE
New paintbrush idea

### ISSUE THREAD

**Issue by Wavehive45** [Runsafe/CreativeToolbox#17]
I think when a user writes /ct p in creative, instead for a blaze rod that you 'paint with' a block appears in your inventory (Maybe different colours of wool for different paintbrushes, i will come to that later) and you build with it. When you type in a command, the block changes
 
I know this would require alot of coding for this but it is better that the current paintbrush...

Commands for this:

/ct p conjur <number> - creates a paintbrush, i think there should be multiple paintbrushes so it is easier to use and of course there would be a limitation to the number of paintbrushes you can conjur, Maybe 3 or 4?

/ct p convert <number>  <block to change to>  This converts the paint block to another block

/ct p <number> save - This would save the paint block and not let it be used to build, only to convert, the saved paintbrushes would be called "paintbrush save 1" or something of the sort.

So examples: 

/ct p 1 - "Conjured paintbrush 1 <then all the other jazz>"

/ct p convert 1 double_step - "Paintbrush 1 converted to Double_Step!"

/ct p 1 save - "saved your paintbrush 1! You can now use this to only convert the blocks you used with this paintbrush"

I hope this gets taken into consideration even though it is very complicated, it will make alot of builders' life easier so that they can control their builds better.

Thanks

Wavehive45

**Comment by Kruithne** [comment]
The coding aside, this as a feature is a bit more complicated than we'd like for a feature of the server. For the most part, the paintbrush achieves this is a simple form without being overly complicated for users to understand.
